### ISSUE TITLE
Error with OpenFilePicker

### ISSUE THREAD

**Issue by naleo** [alxcube/fsa-mock#1]
I am getting this error when trying to use the mock.

![image](https://github.com/alxcube/fsa-mock/assets/2079998/0e439248-87d7-4d5c-9750-90b934569793)

**Comment by alxcube** [comment]
> I am getting this error when trying to use the mock.
> 
> ![image](https://private-user-images.githubusercontent.com/2079998/324948029-0e439248-87d7-4d5c-9750-90b934569793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTYyNzEsIm5iZiI6MTcxMzg5NTk3MSwicGF0aCI6Ii8yMDc5OTk4LzMyNDk0ODAyOS0wZTQzOTI0OC04N2Q3LTRkNWMtOTc1MC05MGI5MzQ1Njk3OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTgxMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNiOWE0MDYwYTU3Y2ZlNDBmODA0Y2FiYzBhNGY1YzVlMmMxN2MxZjEzZTU3ZmJiMGUxYzU1NmRhNDBmZTVjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bKr6GddTi9oS_s5X2OJ2BEA_LBbc7KELtmBj6cag6Yg)

You should always return array of paths from `onOpenFilePicker` callback:
```ts
const path = "path/to/file.txt";
mock.onOpenFilePicker(() => [path]);
```

**Comment by naleo** [comment]
Ahh, thank you for the help!
